import { access, readFile } from "node:fs/promises";
import { constants } from "node:fs";

const required = [
  "server.js",
  "src/app.js",
  "src/config/env.js",
  "src/models/Product.js",
  "src/models/Order.js",
  "src/models/Coupon.js",
  "src/models/Subscriber.js",
  "src/models/ContactMessage.js",
  "src/routes/admin.js",
  "src/routes/public.js",
  "src/routes/payments.js",
  "src/services/orderService.js",
  "src/services/paystack.js",
  "src/services/quote.js",
  "src/services/orderWorkflow.js",
  "src/services/inventory.js",
  "src/services/inventoryMigration.js",
  "src/services/email.js",
  "src/services/upload.js",
  "scripts/check-paystack.js",
  "scripts/check-email.js",
  "views/store.ejs",
  "assets/js/app.js",
  "assets/css/styles.css",
  "assets/images/footprint.png",
  ".env.example",
  "Dockerfile",
  "compose.yaml",
  "DEPLOYMENT.md",
];

required.push(
  ...[
    "pics1.jpeg",
    "pics2.jpeg",
    "pics3.jpeg",
    "pics4.jpeg",
    "pics7.jpeg",
    "pics8.jpeg",
    "pics10.jpeg",
    "pics11.jpeg",
    "pics12.jpeg",
    "pics13.jpeg",
    "pics14.jpeg",
    "pics15.jpeg",
    "pics16.jpeg",
    "pics17.jpeg",
    "pics18.jpeg",
    "pics19.jpeg",
    "pics20.jpeg",
    "pics21.jpeg",
    "pics22.jpeg",
    "pics23.jpeg",
    "pics24.jpeg",
    "logo.jpeg",
    "instagram.png",
    "tiktok.png",
    "whatsapp.png",
    "phone-call.png",
    "down-arrow.png",
  ].map((filename) => `assets/images/${filename}`),
);

for (const path of required) await access(path, constants.R_OK);

const [
  client,
  styles,
  productModel,
  orderModel,
  adminRoutes,
  publicRoutes,
  paymentRoutes,
  paystackService,
  orderService,
  workflow,
  envConfig,
  envExample,
  paystackCheck,
  emailCheck,
  inventoryService,
  inventoryMigration,
  seedScript,
] = await Promise.all([
  readFile("assets/js/app.js", "utf8"),
  readFile("assets/css/styles.css", "utf8"),
  readFile("src/models/Product.js", "utf8"),
  readFile("src/models/Order.js", "utf8"),
  readFile("src/routes/admin.js", "utf8"),
  readFile("src/routes/public.js", "utf8"),
  readFile("src/routes/payments.js", "utf8"),
  readFile("src/services/paystack.js", "utf8"),
  readFile("src/services/orderService.js", "utf8"),
  readFile("src/services/orderWorkflow.js", "utf8"),
  readFile("src/config/env.js", "utf8"),
  readFile(".env.example", "utf8"),
  readFile("scripts/check-paystack.js", "utf8"),
  readFile("scripts/check-email.js", "utf8"),
  readFile("src/services/inventory.js", "utf8"),
  readFile("src/services/inventoryMigration.js", "utf8"),
  readFile("src/scripts/seed.js", "utf8"),
]);

const noDemoPaymentSource = ![
  client,
  adminRoutes,
  publicRoutes,
  paymentRoutes,
  orderService,
  envConfig,
  envExample,
].some((source) =>
  /demo-pay|demoToken|PAYMENT_MODE|Simulate successful payment|provider\s*===\s*["']demo["']/i.test(
    source,
  ),
);

const assertions = [
  [styles.includes(".site-header .brand-word{display:inline-flex}"), "mobile brand name override"],
  [client.includes("Delivery fee per pair"), "admin delivery-fee input"],
  [client.includes("Available sizes and stock"), "admin per-size inventory editor"],
  [client.includes("data-add-custom-size") && client.includes("data-remove-custom-size"), "custom-size add/remove controls"],
  [client.includes('type="submit" class="btn btn-acid">Save sneaker'), "explicit sneaker form submit control"],
  [client.includes("Shown as sold out"), "sold-out size management guidance"],
  [client.includes("size-btn") && client.includes("aria-disabled"), "customer sold-out size controls"],
  [client.includes("Product delivery fees"), "checkout delivery-fee summary"],
  [productModel.includes("deliveryFee"), "product delivery-fee field"],
  [productModel.includes("sizeInventory"), "product per-size inventory field"],
  [adminRoutes.includes("inventoryFields(body.sizeInventory)"), "validated per-size product CRUD"],
  [inventoryService.includes("inventoryStockForSize"), "size-specific availability checks"],
  [inventoryService.includes("normalizeShoeSize") && inventoryService.includes("MAX_SIZES_PER_PRODUCT"), "custom-size server validation"],
  [inventoryMigration.includes("bulkWrite"), "legacy inventory migration"],
  [orderService.includes('"sizeInventory.$[selectedSize].stock"'), "atomic per-size stock updates"],
  [adminRoutes.includes('\"/products/:id\"'), "product update endpoint"],
  [adminRoutes.includes("Product.findByIdAndUpdate") && adminRoutes.includes('returnDocument: "after", runValidators: true'), "atomic validated product editing"],
  [client.includes("/api/orders"), "live checkout connection"],
  [publicRoutes.includes('\"/orders/lookup\"'), "customer order tracking endpoint"],
  [publicRoutes.includes('\"/orders/quote\"'), "server-side cart quote endpoint"],
  [adminRoutes.includes('\"/coupons\"'), "promotion management endpoints"],
  [adminRoutes.includes('\"/messages\"'), "contact-message management endpoints"],
  [adminRoutes.includes('\"/subscribers\"'), "subscriber management endpoints"],
  [adminRoutes.includes('\"/account/password\"'), "admin password-change endpoint"],
  [orderModel.includes("statusHistory"), "order status history"],
  [orderModel.includes("discount"), "order discount persistence"],
  [orderService.includes("applyCouponToQuote"), "server-validated promotion calculation"],
  [client.includes('data-route="/wishlist"'), "wishlist customer page"],
  [client.includes('data-route="/track-order"'), "order-tracking customer page"],
  [client.includes("data-new-coupon"), "promotion dashboard UI"],
  [client.includes("data-message-status"), "message dashboard UI"],
  [client.includes("data-subscriber-toggle"), "subscriber dashboard UI"],
  [client.includes('name="featured"'), "featured-product admin control"],
  [orderModel.includes("inventoryRestockedAt"), "cancelled-order inventory restock marker"],
  [orderService.includes("restockOrderInventory"), "inventory restock service"],
  [workflow.includes("unpaid") || workflow.includes("has not been paid"), "unpaid-order fulfilment guard"],
  [client.includes("Confirming your order."), "verified payment-success UX"],
  [adminRoutes.includes('\"/orders/:reference/refund\"'), "admin full-refund endpoint"],
  [paystackService.includes('paystackRequest("/refund"'), "Paystack refund integration"],
  [paymentRoutes.includes('\"refund.processed\"'), "Paystack refund webhook lifecycle"],
  [orderModel.includes("needs-attention") && orderModel.includes("refundedAt"), "refund state persistence"],
  [client.includes("data-refund-order"), "admin refund control"],
  [orderService.includes("wasCancelledBeforePayment"), "late-payment cancellation guard"],
  [publicRoutes.includes("normalizePhoneForMatch"), "format-tolerant order tracking"],
  [envConfig.includes("PAYSTACK_PUBLIC_KEY") && envConfig.includes("PAYSTACK_SECRET_KEY"), "Paystack public/secret key configuration"],
  [envConfig.includes('paystackEnvironment !== "live"'), "production live-key enforcement"],
  [envConfig.includes('PAYSTACK_CALLBACK_URL must be the /payment/callback route on APP_URL'), "production callback origin enforcement"],
  [paystackService.includes("assertPaystackEnvironment(transaction?.domain)"), "Paystack live/test domain verification"],
  [paystackService.includes("transactionEmail") && paystackService.includes("expectedAmount"), "Paystack customer/amount verification"],
  [paymentRoutes.includes("x-paystack-signature") && paymentRoutes.includes("paystackSignature"), "signed Paystack webhook verification"],
  [publicRoutes.includes("authorizationUrl") && publicRoutes.includes("assertPaystackConfigured"), "Paystack-only order initialization"],
  [client.includes("Paystack checkout unavailable") && !client.includes("data-payment-success"), "no simulated frontend payment path"],
  [orderModel.includes('enum: ["paystack"]'), "Paystack-only payment provider persistence"],
  [paystackCheck.includes('paystackRequest') || paystackCheck.includes("verifyPaystackCredentials"), "live Paystack credential verification command"],
  [emailCheck.includes("verifyEmailConnection"), "SMTP credential verification command"],
  [noDemoPaymentSource, "demo payment paths removed"],
  [![adminRoutes, publicRoutes, orderService, seedScript].some((source) => /\bnew\s*:\s*true\b/.test(source)), "deprecated Mongoose update options removed"],
];

for (const [passed, name] of assertions) {
  if (!passed) throw new Error(`Project check failed: ${name}`);
}

console.log(
  `Project check passed: ${required.length} required files and ${assertions.length} feature assertions.`,
);
